### ISSUE TITLE
No AUR package available for installation in Arch based systems

### ISSUE THREAD

**Issue by pastaq** [aarron-lee/steam-powerbuttond#3]
It would be preferable to have an AUR package to install steam-powerbuttond as that would enable ChimeraOS to ship the daemon in the next version after HandyGCCS is retired. If you're not interested or capable of doing this I can maintain it, but I wanted to run it past you first.

**Comment by aarron-lee** [comment]
> It would be preferable to have an AUR package to install steam-powerbuttond as that would enable ChimeraOS to ship the daemon in the next version after HandyGCCS is retired. If you're not interested or capable of doing this I can maintain it, but I wanted to run it past you first.

sorry, didn't see the notification for this issue.

I think it'd be preferable if you maintained it, if possible.

I initially created steam-powerbuttond as a stopgap workaround for rogueenemy, I actually hadn't planned for any long term maintenance, packaging, etc.

edit: steam-powerbuttond has now been transferred to ShadowBlip

**Comment by aarron-lee** [comment]
nice :)
https://aur.archlinux.org/packages/steam-powerbuttond-git
